banks:
  - bank_name: "Starling Personal"
    class_name: StarlingProvider
    library_name: starling
    token_name: STARLING_PERSONAL_TOKEN
  - bank_name: "Starling Business"
    class_name: StarlingProvider
    library_name: starling
    token_name: STARLING_BUSINESS_TOKEN

categories:
  essential:
    - "Groceries"
    - "Energy"
    - "Phone/Internet"
    - "Transport"
    - "Household"
    - "Health"
  discretionary:
    - "Entertainment"
    - "Clothing"
    - "Garden"
    - "Hobbies"
    - "Other"

default_interval_days: 14
default_transaction_limit: 20